module.exports.RUN_BLOCK_CHAIN_SUCCESS = 0;
module.exports.RUN_BLOCK_CHAIN_SOME_TRANSACTIONS_INVALID = 1;
module.exports.RUN_BLOCK_CHAIN_PARENT_BLOCK_NOT_EXIST = 2;
module.exports.RUN_BLOCK_CHAIN_VALIDATE_FAILED = 3;
